### ISSUE TITLE
Slows down site

### ISSUE THREAD

**Issue by JohanWinther** [NorthStarMarketing/sign-in-with-google#11]
The plugin slows down my Wordpress site a bit. Is it possible to only load the plugin when necessary? Perhaps only when the user is logged out and on the relevant pages (login page and google response page).

EDIT: Checked out the code a bit and I wonder if it is the loading of the dependencies on every page load that slows it down.

**Comment by tarecord** [comment]
@JohanWinther that's definitely a good idea. I haven't noticed any loading issues with the sites I have it on, but I'll dig in and test a little more. Feel free to submit a PR if you figure something out!

**Comment by JohanWinther** [comment]
Apparently it was another plugin that used sessions incorrectly.
