### ISSUE TITLE
Fails When Redirecting After User Logs Out

### ISSUE THREAD

**Issue by tarecord** [NorthStarMarketing/sign-in-with-google#21]
After users log out, they see the login form. From here, they are able to log back in, however, the redirect back fails with just a white screen after they are authenticated with Google.

**Steps To Reproduce:**
1. Sign in to the site
2. Log Out
3. From the `wp-login.php?loggedout=true` screen, click the "Sign In With Google" button
4. See the white screen

**Comment by JohanWinther** [comment]
The blank screen only appears when the `redirect_to` url variable is not set.
