### ISSUE TITLE
Show log in with Google button on custom login form

### ISSUE THREAD

**Issue by lucguerraz** [NorthStarMarketing/sign-in-with-google#28]
Hey,

Is there a way to show the log in with Google button in a custom login form?

for example in this:
`<form method="post" action="<?php echo wp_login_url(); ?>">
    <input type="text" name="log">
    <input type="password" name="pwd">
    <input type="submit" name="wp-submit" value="Login" ></form>
`

Thanks in advanced for the help

**Comment by tarecord** [comment]
@lucguerraz it only displays on the WordPress login page, but that sounds like it could be useful (in a sidebar for example).

Could you provide a little more detail on your specific use case?

**Comment by lucguerraz** [comment]
hi @tarecord thanks for your reply.

 I have a custom login form using this code: `<form method="post" action="<?php echo wp_login_url(); ?>"> <input type="text" name="log"> <input type="password" name="pwd"> <input type="submit" name="wp-submit" value="Login" ></form>`  in my footer and want to show the login with google button there.

Is there a way to do this? - either by using `do_action()` or by putting some custom code there?

Thanks
